PROFILES = {
    'default': {
        'internetbundle': '100MB',
        'belbundle': '150bel/sms',
        'simcard': 'standaard',
        'gender': 'male',
        'firstname': 'test',
        'lastname': 'test',
        'initials': 't',
        'day': '1',
        'month': '1',
        'year': '1990',
        'postcode': '5331XW',
        'housenumber': '7',
        'phonenumber': '0612345678',
        'email': 'test@test.nl',
        'repeat_email': 'test@test.nl',
        'idtype': 'drivers_licence',
        'IBAN_number': 'NL20INGB0001234567',
        'document_number': '3131313131',
        'porting': 'nee',
        'services': 'standaardinstellingen',
        'click&collect': False,
        'delivery': True,
    }
}